name: Pipeline CI/CD Complet

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verification_qualite:
    name: Verification de la Qualite du Code
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des dependances de test
        run: pip install flake8

      - name: Analyse syntaxique et standards (Flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  construction_et_securite:
    name: Construction et Analyse de Securite
    needs: verification_qualite
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Construction de l'image Docker
        run: docker build -t tp-app:${{ github.sha }} app/

      - name: Analyse des vulnerabilites (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tp-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Sauvegarde de l'image Docker
        run: docker save -o /tmp/image-docker.tar tp-app:${{ github.sha }}

      - name: Televersement de l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: image-docker
          path: /tmp/image-docker.tar
          retention-days: 1

  test_fonctionnel:
    name: Test Fonctionnel de l'Application
    needs: construction_et_securite
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation de l'artefact Docker
        uses: actions/download-artifact@v4
        with:
          name: image-docker
          path: /tmp

      - name: Chargement de l'image Docker
        run: docker load -i /tmp/image-docker.tar

      - name: Demarrage du conteneur de test
        run: docker run -d -p 8080:5000 --name conteneur-test tp-app:${{ github.sha }}

      - name: Attente du demarrage du service
        run: sleep 5

      - name: Verification du point de terminaison de sante
        run: curl -f http://localhost:8080/health

      - name: Affichage des logs en cas d'echec
        if: failure()
        run: docker logs conteneur-test