name: CI - Pipeline DevOps

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-sec:
    name: Build, Sécu & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Analyse du code (Flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build de l'image Docker
        run: docker build -t tp-app:${{ github.sha }} app/

      - name: Scan de vulnérabilités (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tp-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Lancement du conteneur
        run: docker run -d -p 8080:5000 --name test-app tp-app:${{ github.sha }}

      - name: Attente démarrage
        run: sleep 5

      - name: Vérification de l'API (/health)
        run: curl -f http://localhost:8080/health

      - name: Logs du conteneur (si échec)
        if: failure()
        run: docker logs test-app